#!/usr/bin/env bash
# Reads the last 2 CI reports from /srv/syrex-api/logs/ and writes a
# nicely formatted markdown summary to /home/ashish/deployed_logs.md.
# Called automatically by CI after each run; also safe to run manually.
set -euo pipefail

LOGS_DIR="/srv/syrex-api/logs"
OUTPUT="/home/ashish/deployed_logs.md"

mapfile -t REPORTS < <(ls -t "$LOGS_DIR"/ci-*.txt 2>/dev/null | head -2)

icon() { [ "${1:-}" = "success" ] && echo "✅  success" || echo "❌  ${1:-unknown}"; }

extract_section() {
  local file="$1" start="$2" stop="$3"
  awk "/^${start}/{f=1;next} /^${stop}/{f=0} f" "$file" | sed '/^[[:space:]]*$/d'
}

parse_field() {
  grep "^${1}" "$2" 2>/dev/null | sed 's/^[^:]*: //' | tr -d '\r'
}

{
  echo "# Syrex — Deployed Logs"
  echo ""
  echo "> Auto-generated by CI · Last updated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
  echo "> Run \`~/gen_deployed_logs.sh\` to refresh manually."
  echo ""

  if [ "${#REPORTS[@]}" -eq 0 ]; then
    echo "_No CI reports found in \`${LOGS_DIR}\` yet._"
    exit 0
  fi

  for i in "${!REPORTS[@]}"; do
    FILE="${REPORTS[$i]}"
    N=$((i + 1))

    TIMESTAMP=$(parse_field "Timestamp" "$FILE")
    COMMIT=$(parse_field "Commit" "$FILE")
    BRANCH=$(parse_field "Branch" "$FILE")
    ACTOR=$(parse_field "Actor" "$FILE")
    BACKEND=$(parse_field "Backend" "$FILE")
    WEB=$(parse_field "Web" "$FILE")
    SHORT="${COMMIT:0:8}"

    # Overall status for section header
    if [ "$BACKEND" = "success" ] && [ "$WEB" = "success" ]; then
      OVERALL="✅  All checks passed"
    else
      OVERALL="❌  CI failed"
    fi

    echo "---"
    echo ""
    echo "## ${N}. \`${SHORT}\` — ${BRANCH}"
    echo ""
    echo "> ${OVERALL}"
    echo ""
    echo "| Field   | Value |"
    echo "|---------|-------|"
    echo "| Time    | \`${TIMESTAMP}\` |"
    echo "| Author  | ${ACTOR} |"
    echo "| Commit  | \`${COMMIT}\` |"
    echo ""
    echo "### Check results"
    echo ""
    echo "| Check                | Result |"
    echo "|----------------------|--------|"
    echo "| Backend typecheck    | $(icon "$BACKEND") |"
    echo "| Web build + lint     | $(icon "$WEB") |"
    echo ""

    BE_RAW=$(extract_section "$FILE" "--- Backend Typecheck ---" "--- Web Build")
    WEB_RAW=$(extract_section "$FILE" "--- Web Build \+ Lint ---" "={5,}")

    # Pull out warning lines for a quick summary
    BE_WARNS=$(echo "$BE_RAW" | grep -i 'warning' || true)
    WEB_WARNS=$(echo "$WEB_RAW" | grep -i 'warning' || true)

    if [ -n "$BE_WARNS" ] || [ -n "$WEB_WARNS" ]; then
      echo "### ⚠️  Warnings"
      echo ""
      echo '```'
      [ -n "$BE_WARNS"  ] && { echo "## backend"; echo "$BE_WARNS"; }
      [ -n "$WEB_WARNS" ] && { echo "## web";     echo "$WEB_WARNS"; }
      echo '```'
      echo ""
    fi

    echo "<details>"
    echo "<summary>Full backend typecheck output</summary>"
    echo ""
    echo '```'
    echo "${BE_RAW:-(no output)}"
    echo '```'
    echo ""
    echo "</details>"
    echo ""
    echo "<details>"
    echo "<summary>Full web build + lint output</summary>"
    echo ""
    echo '```'
    echo "${WEB_RAW:-(no output)}"
    echo '```'
    echo ""
    echo "</details>"
    echo ""
  done

  echo "---"
  echo ""
  echo "_Full per-run logs: \`${LOGS_DIR}/ci-<sha>.txt\` · Summary index: \`${LOGS_DIR}/ci-summary.log\`_"

} > "$OUTPUT"

echo "Wrote ${OUTPUT}"
